create table if not exists public.progress_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_key text not null,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  unique (user_id, storage_key)
);

alter table public.progress_entries enable row level security;

drop policy if exists "Users can read their own progress entries" on public.progress_entries;
create policy "Users can read their own progress entries"
  on public.progress_entries
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can create their own progress entries" on public.progress_entries;
create policy "Users can create their own progress entries"
  on public.progress_entries
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own progress entries" on public.progress_entries;
create policy "Users can update their own progress entries"
  on public.progress_entries
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own progress entries" on public.progress_entries;
create policy "Users can delete their own progress entries"
  on public.progress_entries
  for delete
  to authenticated
  using (auth.uid() = user_id);
